### ISSUE TITLE
Google Icon Review

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2364]
As mentioned in #1919: having come across https://partnermarketinghub.withgoogle.com/#/brands, we should probably review all of our Google-related icons, PRs & issues that are covered on that site to ensure our icons & colours are correct. The relevant ones are (if I've missed any, please add them to the list):

- [ ] ~Android~ (has its own brand guidelines)
- [ ] ~Google Assistant~ (logo downloads require login)
- [x] Google Cast
- [x] Google Fit
- [x] Google Lens
- [x] Google Pay
- [ ] ~Google Photos~ (monochrome not permitted)
- [ ] ~Google Play~ (monochrome version not available for download)
- [x] Google Street View
- [ ] ~Stadia~ (access requires login)
- [ ] ~Wear OS~ (access requires login)
- [ ] ~YouTube~ (has its own brand guidelines)

**Comment by ericcornelissen** [comment]
Android was recently updated after a the report in #1605 with Pull Request #1717 based on [the brand guidelines from developer.android.com](https://developer.android.com/distribute/marketing-tools/brand-guidelines). The SVG, as far as I can tell, match exactly. The only difference is that the colour we use is `#3ddc84`, which is explicitly stated on the site linked above, and the SVGs (from both the old and new source) use `#3ddc85`. Unfortunately, the [colour palette for Android](https://partnermarketinghub.withgoogle.com/#/brands/1KdZxnHbtjVwReGOY03iKT8DDx1Y34joI/16oEtfCF_WEoXVG5WVoIPyA0bQGf9jzmDZfgNnkMXSsM) is not accessible by me so I can't confirm this... Maybe someone else has more luck?

All in all, I do think we could update the URL to ⬇️ even though it is a very ugly URL 😞 

```
https://partnermarketinghub.withgoogle.com/#/brands/1KdZxnHbtjVwReGOY03iKT8DDx1Y34joI
```

**Comment by PeterShaggyNoble** [comment]
When contradictions or inconsistencies arise - it's Google, they're *going* to be plentiful :laughing: - we should favour the product's dedicated brand guidelines as they're most likely to be accurate. So, in this case, I'd say Android is fine as it is.

**Comment by PeterShaggyNoble** [comment]
Similarly, as YouTube have their own dedicated guidelines, let's check them off the list.

**Comment by PeterShaggyNoble** [comment]
Added Google Street View to the list as I found an official vector version at https://developers.google.com/streetview/ready/branding

Will try to make time tomorrow to go through all these - I'd completely forgotten about this issue!

**Comment by PeterShaggyNoble** [comment]
Between a lot of things requiring login and a few brands having their own guidelines, there's not much to be actioned here:
- The Fit, Lens, Pay & Street View icons need to be updated
- The Pay, Play & Street View colours need to be updated
- The source URL for Google Play needs to be changed (don't know what that site _was_) - https://partnermarketinghub.withgoogle.com/#/brands/ unless someone has a better suggestion

Based on [this](https://partnermarketinghub.withgoogle.com/#/brands/1Mieqs9mxqr9npLHgbaiOsNJtbhn5XVWW/1L9ExuGEFk1s6RcM4skpmPAKEgyJZcmP3eyiVoAknhN0) should we change the colour of Google Assistant to red? They don't state a preference so I think we're OK to continue using the blue.

I'll get a PR together with all these changes shortly.

**Comment by PeterShaggyNoble** [comment]
We'll need to find a source for the Wear OS logo as [this page](https://partnermarketinghub.withgoogle.com/#/brands/10Ac6-b7cYyfiCP4foFIe8Ag50iMLaM-q/1PdNFPeQaLSEFBcVSz7P3oQdPgsfR_pd3N043WGqDVv4) states:

> In marketing creative, the Wear OS by Google icon should not be featured alone. Always use the icon as a part of the logo lockup (including the Wear OS by Google wordmark). As an exception, when using the icon in the context of a home screen UI, it may be featured alone.
>
>...
>
>![image](https://user-images.githubusercontent.com/15157491/75560215-a9b57300-5a3c-11ea-9ff4-f5159032f846.png)
>**DON'T**
>Do not use the W icon alone.

**Comment by ericcornelissen** [comment]
> Between a lot of things requiring login and a few brands having their own guidelines, there's not much to be actioned here:
> 
> [...]
>
> I'll get a PR together with all these changes shortly.

Thanks for doing the hard work of going through all these @PeterShaggyNoble! :+1:


> We'll need to find a source for the Wear OS logo as [this page](https://partnermarketinghub.withgoogle.com/#/brands/10Ac6-b7cYyfiCP4foFIe8Ag50iMLaM-q/1PdNFPeQaLSEFBcVSz7P3oQdPgsfR_pd3N043WGqDVv4) states:
> [...]

That's a pity :disappointed: Though the wording is a bit confusing to me: "**In marketing creative,** the Wear OS by Google icon should not be featured alone." Is it safe to assume that we operate outside that scope?

And "when using the icon in **the context of a home screen UI**, it may be featured alone. " Only a home screen UI and not UI in general? I don't think the logo changes in the app drawer :thinking: 

Under the assumption that our icons will be used in a "screen UI" I think we can leave it as is, or if we find an official source that is a bit clearer. Otherwise we may have to remove it... (I don't think it is sensible to include "Wear OS by Google" in the SVG)

**Comment by PeterShaggyNoble** [comment]
> Is it safe to assume that we operate outside that scope?

For the sake of _not_ having to include the wordmark (or remove the icon altogether), I'm more than happy to make that same assumption! 😆
