### ISSUE TITLE
Automated fixes in Pull Requests

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/simple-icons#2380]
Opening this issue to discuss the possibility of implementing automated fixes in Pull Requests first(?) discussed in #2334. Some things that we could automatically fix by pushing commits are:

- [ ] Uppercase hex value
- [ ] Add `<title>` to SVG when it is missing based on the title in the JSON
- [ ] Run `npm run svgo -- [icon]` for the new SVG (see also #2061)
- [ ] Order JSON file alphabetically
- [ ] Pretiffy JSON file
- [ ] The treatment of newlines
- [ ] Remove `#` from the hex field if it is accidentally included
- [ ] Unify implicit/explicit closepath commands (see also #5070)

More suggestions for things we could automate are welcome 🙂

**Comment by PeterShaggyNoble** [comment]
In case they're not covered by "SVG optimisation" above:

- Strip `doctype`s
- Strip newlines & tabs
- Add missing attributes to `svg` tag and strip unnecessary attributes
- Replace `<path d="..." />" and "<path d="..."></path>` with `<path d="..."/>`
- Strip unnecessary attributes from `path` tag

**Comment by ericcornelissen** [comment]
By "SVG optimization" I basically meant "Run `npm run svgo -- [icon]` for the new SVG" 😄 (updated original for clarity)

**Comment by runxel** [comment]
- The treatment of newlines

**Comment by ericcornelissen** [comment]
Good one @runxel 👍 updated the issue description

**Comment by phatbhoy67** [comment]
I have included the # in the hex value more than once.............. 😆

**Comment by ericcornelissen** [comment]
I'm currently in the process of creating a GitHub action to "Run `npm run svgo -- [icon]` for the new SVG" 🙂 see: https://github.com/ericcornelissen/svgo-action

**Comment by ericcornelissen** [comment]
@mondeja [brought up](https://github.com/simple-icons/simple-icons/issues/5070#issuecomment-782213396) that doing automated fixes in Pull Requests might be 1) perceived as being invasive and 2) confusing for newcomers (_"huh, I can't push because my branch is out of sync?"_). And that we should instead consider pushing automated fixes AFTER the pull request has been merged, especially since some of these things are quite trivial.

I'm personally still of the opinion that we should do the fixes within the context of a Pull Request so as to avoid merging in "invalid" (*) Pull Requests for the following reasons:

- If the automated fix somehow fails on `develop` all other PRs become invalid because `develop` is now invalid. This problem is local to the Pull Request that is being automatically fixed.
- By carefully communicating what happens with the contributor, e.g. by commenting on the PR, we can avoid the impression of invasiveness and potentially even help newcomers with any difficulty they might face due to the new commit
- Even though most of these fixes are trivial and arguably fine on `develop`, some, like running `svgo` automatically, aren't and require manual review. I would be against splitting the automated fixes to different places to make keeping track of them easier in the long run.
- Prevent having "unnecessary" commits on `develop`

<sup>(*) "invalid" in the sense that it is not the way we want it to be on `develop` and `master`.</sup>

**Comment by mondeja** [comment]
I see your point. Probably this "huh, I can't push because my branch is out of sync?" feeling could be prevented if we create a comment in fixed pull requests explaining to contributors in a comment how to pull the changes to their local branches.

**Comment by ericcornelissen** [comment]
Closing this out for now as it has turned out this is somewhat difficult to implement using GitHub actions due to access restrictions on Pull Request for forks.

That said, if anyone has ideas for how we might be able to implement this, please leave a comment so we can reconsider.

**Comment by ericcornelissen** [comment]
I was studying the `stefanzweifel/git-auto-commit-action` documentation for #6646 and stumbled on [the "Advanced Uses" section](https://github.com/stefanzweifel/git-auto-commit-action#advanced-uses) and it would seems we might be able to get automated fixes working if we ask contributors to enable actions on their fork.

I haven't tested this yet but re-opening this issue as there are new options on the table. Some things that I think should be tested before actually implementing this:

- Does it actually work if set up correctly?
- If a contributor does not properly set up their fork, will the workflow error or just not commit anything?

If you have other concerns, please leave a comment.

**Comment by sachinraja** [comment]
Is it possible to have a workflow on `pull_request` that pushes to the contributor's branch if they enabled edits?

**Comment by ericcornelissen** [comment]
I think a pre-commit hook won't be sufficient for all of the contributions we receive. Lots of contributors do so without ever running `npm install`, so they won't benefit from the pre-commit hooks. Not to mention that I'd wager that some of the people that would benefit from it the most are also the people least likely to run `npm install`.

That said, adding a pre-commit hook wouldn't hurt.

**Comment by adamrusted** [comment]
I'm going to close this out for now. I'm also of the opinion that adding validation on the GitHub side will be too invasive for a lot of our contributors, and we now have the husky pre-commit hooks working away anyway (for those of us that `npm install`!
