### ISSUE TITLE
Adobe Icon Review

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2734]
In light of #2733, and following on from #2364, we should do a full review of all of our Adobe icons. Most all of their brands have their own product pages (e.g., [Phostoshop](https://www.adobe.com/products/photoshop.html)) with SVG logos.

- [x] Adobe (#2769)
- [x] Adobe Acrobat Reader (#2769)
- [x] Adobe After Effects (#2769)
- [x] Adobe Audition (#2769)
- [x] Adobe Creative Cloud (#2769)
- [x] Adobe Dreamweaver (#2769)
- [x] Adobe Illustrator (#2769)
- [x] Adobe InDesign (#2769)
- [x] Adobe Lightroom CC
- [x] Adobe Lightroom Classic
- [x] Adobe PhoneGap
- [x] Adobe Photoshop (#2733)
- [x] Adobe Premiere (#2770)
- [x] Adobe Typekit (#2771, #2776)
- [x] Adobe XD

**Comment by PeterShaggyNoble** [comment]
Closing this out as I have the rest of these ready to go once #2769 is merged (I stupidly worked on the same branch! 🙄)
