### ISSUE TITLE
Update Icon Request template

### ISSUE THREAD

**Issue by NovaGL** [simple-icons/simple-icons#3200]
### Kind of issue 
  - [X] Improvement
  - [ ] Bug
  - [ ] Other, namely:

### Description
I think the template for Icon Requests should be updated.

There should be some guidelines on acceptable icons.
Eg, please lookup the Alexa site ranking, please note icons with rankings over 500K might not be accepted.

Alternatively please mention other metrics you have used to display the popularity of this brand.

**Comment by PeterShaggyNoble** [comment]
Good idea, @NovaGL :+1: I've been toying with the same idea myself for a while.

I do think we should add the Alexa rank to the issue template and, perhaps, the PR template as well for contributions without an issue. The first thing most all of us do when a new request comes in is check the rank, so this would be one less thing for us to do. But I don't think we need to go into too much detail about it, as it's already covered in our contributing guidelines. Nor do I think we should request any other metric as they are not yet clearly defined; our guidelines currently state:
> For anything else, popularity will be judged on a case-by-case basis.

We also want to minimise the amount of leg-work we expect people to put in when requesting an icon; finding official resources alone can take a while.

So, I would suggest, for the issue template, something along the lines of:
```
<!--
  We won't add non-brand icons or anything related to illegal services.
  If in doubt open an issue and we'll have a look.

  Before opening a new issue search for duplicate or closed issues.

  When requesting a new icon please provide the following information:
-->

**Name:**
**Website:**
**Official resources for icon and color:**
  <!-- for example media kits, brand guidelines, SVG files, ...) -->

**Alexa rank:**
  <!-- The Alexa rank can be retrieved at https://www.alexa.com/siteinfo/
       Please see our contributing guidelines at
       https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md
       for more details on how we assess a brand's popularity. -->
```

And, for the PR template:
```
<!--
Before opening your pull request, have a quick look at our contribution guidelines:
https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md

Consider adding a preview image of your submission using:
https://petershaggynoble.github.io/MDI-Sandbox/simpleicons/preview/
-->

**Issue:**

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json`
  - [ ] I optimized the icon with SVGO or SVGOMG
  - [ ] The SVG `viewbox` is `0 0 24 24`

### Description
<!--
Anything relevant, for example:
  - Why did you pick the hex value?
  - Did you manually vectorize the logo?
  - Have you used multiple sources?
  - etc.

**Alexa rank:**
  <!-- The Alexa rank can be retrieved at https://www.alexa.com/siteinfo/
       Please see our contributing guidelines at
       https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md
       for more details on how we assess a brand's popularity. -->
-->
```

**Comment by ericcornelissen** [comment]
Sounds reasonable. Regarding the issue template: I would put the Alexa ranking between the "Website" and "Official resources". Regarding the PR template I would put it right after the "Issue".

**Comment by PeterShaggyNoble** [comment]
Yep, that seems like a better placement for it in the issue template; it invites more detail on the sourcing.

The reason I'd suggest placing it at the end of the PR template is to downplay as, the majority of the time, we're already going to know the rank from the issue. That alone may be a case _against_ adding it to the PR template.

**Comment by ericcornelissen** [comment]
> Yep, that seems like a better placement for it in the issue template; it invites more detail on the sourcing.

👍 

> The reason I'd suggest placing it at the end of the PR template is to downplay as, the majority of the time, we're already going to know the rank from the issue. That alone may be a case against adding it to the PR template.

Fair enough, maybe make explicit that it's only needed if there is no issue for the PR instead? Putting it at the end like that just makes me afraid people might miss it.

**Comment by PeterShaggyNoble** [comment]
Oo, one way we could do it, if we can get the wording right is to ask for the issue number _OR_ the Alexa rank.

**Comment by PeterShaggyNoble** [comment]
Maybe like so?

```
<!--
Before opening your pull request, have a quick look at our contribution guidelines:
https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md

Consider adding a preview image of your submission using:
https://petershaggynoble.github.io/MDI-Sandbox/simpleicons/preview/
-->

**Issue:**

<!-- OR -->

**Alexa rank:**
  <!-- The Alexa rank can be retrieved at https://www.alexa.com/siteinfo/
       Please see our contributing guidelines at
       https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md
       for more details on how we assess a brand's popularity. -->

### Checklist
...
```

**Comment by ericcornelissen** [comment]
Nice idea 👍 I like it.

One minor thing: I would suggest not adding the link to the contributing guidelines in the comment for the Alexa rank _again_. I'm going to guess that anyone taking the time to read that comment has already read to the top-level comment.

**Comment by NovaGL** [comment]
I think its important for people to know the contributing guidelines in an issue for icon requests as if it is simple they might be able to pull request instead.

The thing I was hoping to avoid is:

- Person creates an issue
- Some one responds do you want to contribute
- Alexa rank is too high to be a valid inclusion

We could even possibly avoid the issue creation at all if we ask them up front do they think they could contribute.

So in the PR template it should say linked issue or alexa ranking.

If its clear and concise more people might contribute.

**Comment by PeterShaggyNoble** [comment]
Oop, can't believe I missed that, @ericcornelissen. _Twice_! 🙈 So the PR template would now be:

```
<!--
Before opening your pull request, have a quick look at our contribution guidelines:
https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md

Consider adding a preview image of your submission using:
https://petershaggynoble.github.io/MDI-Sandbox/simpleicons/preview/
-->

**Issue:**

<!-- OR -->

**Alexa rank:**
  <!-- The Alexa rank can be retrieved at https://www.alexa.com/siteinfo/
       Please see our contributing guidelines at for more details on how we
       assess a brand's popularity. -->

### Checklist
...
```

@NovaGL, if the Alexa rank isn't provided by the person requesting the icon that the first thing one of us will usually do is check it, so the process is actually more like:
- Person creates an issue
- Alexa rank is too low, making the request out of scope if we can't assess its popularity by some other means
- If not, someone asks them if they'd like to contribute

Including the contribution guidelines in the issue template may encourage some people to, as you hope, go direct to PR after reading them.

Do you want to run with this now and put a PR together, @NovaGL?

**Comment by NovaGL** [comment]
Hi @PeterShaggyNoble I'd feel more comfortable if you or one of the maintainers made the PR.

Even though I brought up the idea, you did the hard work.

Maybe there should be an issue topic for documentation? So questions like these can be grouped together.

**Comment by PeterShaggyNoble** [comment]
> I'd feel more comfortable if you or one of the maintainers made the PR

OK :+1: I'll try to get that done today.

> Maybe there should be an issue topic for documentation?

We have the ["docs" label](https://github.com/simple-icons/simple-icons/issues?q=is%3Aissue+label%3Adocs). Or did you have something else in mind?

**Comment by NovaGL** [comment]
I can't assign labels, its blanked out so I just choose a template or am i missing something?

**Comment by PeterShaggyNoble** [comment]
Ah, sorry, I get you know. Could be a good idea, yeah. If you open a PR or issue for it, we can discuss it further there.
