### ISSUE TITLE
Update Adobe Icons

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#3369]
Adobe have recently updated the majority of their product logos so that they all now have filled, square backgrounds with rounded corners so we'll need to update to match. In all cases an SVG of the logo can be found on the individual product's page.

We'll need to decide, too, what to do for the colours and be consistent; either we keep our current colours, use the colour of the background square of the new logo or use the colour of the icon/text from the new logo.

Icons we need to update are:
- [x] Adobe After Effects  (#3378)
- [x] Adobe Audition (#3379)
- [x] Adobe Dreamweaver (#3380)
- [x] Adobe Illustrator (#3377)
- [x] Adobe InDesign (#3381)
- [x] Adobe Lightroom CC (#3397, #3396)
- [x] Adobe Lightroom Classic (#3382)
- [x] Adobe Photoshop (#3376)
- [x] Adobe Premiere Pro (#3384)
- [x] Adobe XD (#3386)

**Comment by MetLee** [comment]
I will update the other icons.

**Comment by PeterShaggyNoble** [comment]
Thanks for taking these on, @MetLee, it's a big help.

**Comment by MetLee** [comment]
According to the websites (https://www.adobe.com/products/photoshop-lightroom.html and https://www.adobe.com/creativecloud/catalog/desktop.html), I suggest that `Adobe Lightroom CC` should be renamed `Adobe Lightroom`.

**Comment by PeterShaggyNoble** [comment]
Yes, I'd agree with that, @MetLee. As it's a breaking change, though, it will need to wait until [v4](https://github.com/simple-icons/simple-icons/milestone/3). Can you create a separate issue so we can add it to that milestone, please?

**Comment by PeterShaggyNoble** [comment]
To clarify: It's just the name change that needs to wait until v4; you can go ahead with the updates to the icon & colour.

**Comment by MetLee** [comment]
> Yes, I'd agree with that, @MetLee. As it's a breaking change, though, it will need to wait until [v4](https://github.com/simple-icons/simple-icons/milestone/3). Can you create a separate issue so we can add it to that milestone, please?

Sure!

**Comment by MetLee** [comment]
#3396

**Comment by PeterShaggyNoble** [comment]
Going to close this out as everything in this issue has been taken care of, pending a decision on the colour choices.

Thanks once again for all your work here, @MetLee :+1:
