### ISSUE TITLE
Google Icons Review (again)

### ISSUE THREAD

**Issue by service-paradis** [simple-icons/simple-icons#4205]
Google recently updated a lot of their logos. Following on from #1919, #3725 & #4134, we should do a full review of all our Google icons (again #2364).

For Google Brands, we should follow Visual Identity Guidelines found at https://partnermarketinghub.withgoogle.com/#/brands or their new site https://thepartnermarketinghub.withgoogle.com/brands/

For Google products, it might be a little bit harder to find good icons to based our work on since there is no specific guidelines pages. We should use the icons from the new redesign. This page was still outdated a few days ago, but looks to have been updated now: https://about.google/products/#all-products

Some of the item listed below might not need to be updated, but should be reviewed.

### Here is the list of Google Brands we currently have:

- [x] Android - #4399
- [x] Android Auto - #4400
- [x] Google Assistant -  #4401
- [x] Google Fit - #4506
- [x] Google Lens - #4402
- [x] Google News - #4474
- [x] Google Pay - #4403
- [x] Google Play - #4505
- [x] Google Stadia - #4503
- [x] Wear OS - doesn't need editing @adamrusted 
- [x] YouTube Music - #4404
- [x] YouTube TV - #4405

### Here is the list of Google Products we currently have:

- [x] Android Studio - #4469
- [x] Gmail - #4470
- [x] Google - #4508
- [x] Google Ads - #4471
- [x] Google AdSense - #4472
- [x] Google Analytics - #4504
- [x] Google Calendar - #4522
- [x] Google Cardboard - #4058
- [x] Chromecast (formerly Google Cast) - #6512
- [x] Google Chat - #4695
- [x] Google Chrome - #4525
- [x] Google Classroom - #6512 
- [x] Google Cloud - Seems to be the same @jorgeamadosoria 
- [x] Google Drive - #6596 
- [x] Google Earth - Seems to be the same @jorgeamadosoria 
- [x] Google Hangouts - Seems to be the same @jorgeamadosoria 
- [x] Google Keep - #6599 
- [x] Google Maps - Seems to be the same @jorgeamadosoria 
- [x] Google Marketing Platform - #6599 
- [x] Google Meet - #6599 
- [x] Google Messages - #6599 
- [x] Google My Business - Seems to be the same @jorgeamadosoria 
- [x] Google Nearby - #4059
- [x] Google Podcasts - Seems to be the same @jorgeamadosoria 
- [x] Google Scholar - #4686
- [x] Google Search Console - Seems to be the same @sachinraja
- [x] Google Sheets - #4685
- [x] Google Street View - #4683
- [x] Google Tag Manager - #4586
- [x] Google Translate - #4584
- [x] Waze - #4583
- [x] YouTube - #4582
- [x] YouTube Gaming - LGTM (adamrusted)
- [x] YouTube Studio - #4581

There is also some Google products/brands requests open right now. The linked resources/colors may be out of date. We will need to be careful when working on/reviewing them.

**Comment by fbernhart** [comment]
How about Stadia, Waze and Gmail? They are as well listed at https://about.google/products/#all-products

From what I can remember: Google Photos, Calendar, Meet, Drive, Keep and Gmail got a new logo recently.

**Comment by service-paradis** [comment]
> How about Stadia, Waze and Gmail?

Thanks, something went wrong when I created the issue. I added them :)

**Comment by adamrusted** [comment]
Wear OS is checked. Doesn't need editing at all. 🙌

**Comment by adamrusted** [comment]
Looking at Gmail icon - shall I include 0.35px lines where the colours change?
![gmail](https://user-images.githubusercontent.com/1830867/102653125-71ffef00-4166-11eb-8686-afe8202c1b22.png)

**Comment by adamrusted** [comment]
SVG found for Gmail, Google Calendar, Google Drive, Google Docs, and Google Meet
`https://www.gstatic.com/apps/signup/resources/products_lockup_icon.svg`

**Comment by adamrusted** [comment]
@simple-icons/maintainers - it looks like consumer-facing side of Google Cast has been renamed to `Chromecast Built-In` (bit of a mouthful!). Shall I compare/update the existing Google Cast logo against the 'Chromecast built in' logo, and we can submit PRs to rename it in v5.0.0?

**Comment by PeterShaggyNoble** [comment]
With the downloads on their marketing hub being temperamental, might I suggest that anyone who is able to access them save copies locally to share with the team for review purposes and that we include a zip of the original in our PRs?

**Comment by PeterShaggyNoble** [comment]
For Google My Business, the following monochrome version is used in the menu of their. Personally, I prefer our current treatment as that appears to a simplified, Materialised treatment, which is something we've rejected in the past, but what does everyone else think?

![](https://user-images.githubusercontent.com/15157491/104918380-92e97900-598c-11eb-9033-31606f5676b5.png)

**Comment by adamrusted** [comment]
> Personally, I prefer our current treatment

I agree. Though it may be worth reviewing the current icon to ensure the gaps are 0.5px, and perhaps smooth out the stroke somewhat, to meet the materialized icon in the middle?

**Comment by Karthik-Nayak98** [comment]
Google pay icon is outdated. Please update the icon. Check their [website](https://pay.google.com/intl/en_in/about/)

**Comment by PeterShaggyNoble** [comment]
Thanks, @Karthik-Nayak98. For tracking purposes, though, and to ensure it doesn't get lost in the shuffle, could you open a new issue or PR for that, please?

**Comment by Karthik-Nayak98** [comment]
Let me try to do that

**Comment by PeterShaggyNoble** [comment]
Strangely, I still see our current icon in use on pay.google.com. But that may just be down to a phased roll out that hasn't made it to Ireland yet. Found an official SVG at https://pay.google.com/gp/promo/p_referrals/static/images/gp3-lockup.svg that we can work off for now.

**Comment by Karthik-Nayak98** [comment]
I am from India. Here the apps are updated with a new logo which is in that link. @PeterShaggyNoble

**Comment by nathanwaters** [comment]
Although they're fairly generic, maybe add Google Docs and Google Forms?

**Comment by service-paradis** [comment]
> @simple-icons/maintainers - it looks like consumer-facing side of Google Cast has been renamed to `Chromecast Built-In` (bit of a mouthful!). Shall I compare/update the existing Google Cast logo against the 'Chromecast built in' logo, and we can submit PRs to rename it in v5.0.0?

@adamrusted I think so!

**Comment by adamrusted** [comment]
> Although they're fairly generic, maybe add Google Docs and Google Forms?

There are SVGs available at:
https://www.google.com/docs/about/
https://www.google.com/forms/about/
Which we could use. Would you like to look at contributing them @nathanwaters?

**Comment by PeterShaggyNoble** [comment]
@nathanwaters, see #5155

**Comment by webserviceXXL** [comment]
What about Google Tasks? This one is missing in the list. 

Preview:
![grafik](https://user-images.githubusercontent.com/3533300/129374391-fa316879-2732-4645-8319-d78628f76267.png)

**Comment by ericcornelissen** [comment]
@webserviceXXL please [open a new issue](https://github.com/simple-icons/simple-icons/issues/new?assignees=&labels=new+icon&template=icon_request.md) if you would like to see Google Tasks added, this issue is intended to keep track of progress on updating Google brands already in the collection.

**Comment by jorgeamadosoria** [comment]
Google Cloud doesn't seem to have any changes. Should it be removed from the list?

Additionally, Google Classroom and Google Cast only seem to have the hexes wrong, but the icons themselves does not seem to change. I've added a PR for the hex change.

**Comment by adamrusted** [comment]
> Google Cloud doesn't seem to have any changes. Should it be removed from the list?

I would just mark it as complete, and put a note next to it saying it doesn't require changes.
 
> Additionally, Google Classroom and Google Cast only seem to have the hexes wrong, but the icons themselves does not seem to change. I've added a PR for the hex change.

Are the sources for these already up to date with an official source? If so, do the new hexes you've proposed match up to the official source?

**Comment by jorgeamadosoria** [comment]
> > Google Cloud doesn't seem to have any changes. Should it be removed from the list?
> 
> I would just mark it as complete, and put a note next to it saying it doesn't require changes.
> 
> > Additionally, Google Classroom and Google Cast only seem to have the hexes wrong, but the icons themselves does not seem to change. I've added a PR for the hex change.
> 
> Are the sources for these already up to date with an official source? If so, do the new hexes you've proposed match up to the official source?

There is a PR for this along the icons mentioned. And the source is the one specified in this very issue.

**Comment by jorgeamadosoria** [comment]
Every icon listed has been reviewed. They are either the same, or have a PR open except WearOS.
I think it makes sense to make a push to check these PRs as Priority 0 tasks so we can close this review @simple-icons/maintainers as fast as possible.

**Comment by mondeja** [comment]
Please, don't close the issue until all PRs are merged because one PR could be closed and this issue will pass unnoticed.

**Comment by dirien** [comment]
Oh @mondeja, that was auto-closed via the PR @jorgeamadosoria linked to. I keep an eye on this!

**Comment by sachinraja** [comment]
I just checked Search Console and the current logo is fine, so all the tasks here are done. Great job everyone!
