### ISSUE TITLE
The 2021 Icon Review

### ISSUE THREAD

**Issue by mondeja** [simple-icons/simple-icons#4590]
Starting with #4589, I open this to track those icons that should be reviewed this year. This issue should serve to review the icons that fail with the new linting rules added in 2021.

## Icons with collinear coordinates in straight lines (#4589)

- [x] Amazon Lumberyard (#4591)
- [x] Andela (#4592)
- [x] Apache JMeter (#7000)
- [x] Apache Maven (#4593)
- [x] Arch Linux (#5172)
- ~~Aseprite~~ (#4692)
- ~~Citroën~~ (#4604)
- [ ] Cocos (#6996)
- [x] Daimler (#4618)
- [x] Disroot (#5173)
- [x] DigitalOcean (#4648)
- [x] Elsevier (#5175)
- [x] Epic Games (#5178)
- [x] FedEx (#5180)
- ~~Fedora~~ (#5540)
- [x] Ferrari (#4778)
- [x] Firefox (#5203)
- [x] Fossa (#4473)
- [x] Furry Network (#6221)
- [x] Gatsby (#4620)
- [x] Giphy (#4621)
- [x] Google Ads (#4471)
- ~~Google Pay~~ (#4604)
- [x] Grubhub (#5168)
- [x] Harbor (#4598)
- [x] Jira Software (#4657)
- [x] Kotlin (#4485)
- [x] Lamborghini (#5169)
- [x] Lenovo (#4477)
- [x] Livestream (#4647)
- [x] ManageIQ (#5165)
- [x] Material Design Icons (#4642)
- [x] Matternet (#6222)
- [x] Microsoft (#4649)
- ~~Minds~~ (#4604)
- [x] Monzo (#5219)
- [x] Mozilla (#4656)
- ~~MusicBrainz~~ (#4604)
- [x] New Japan Pro-Wrestling (#4930)
- [x] ngrok (#5176)
- [x] Notepad++ (#5187)
- [x] OpenAPI Initiative (#6223)
- [x] Packagist (#5182)
- [x] PCGamingWiki (#6224)
- [x] Phabricator (#5143)
- [x] pr.co (#4655)
- [x] PrestaShop (#6225)
- [x] RabbitMQ (#5183)
- [x] Ruby (#6226)
- [x] Server Fault (#6227)
- [x] Showpad (#https://github.com/simple-icons/simple-icons/pull/6999)
- [x] SonicWall (#4654)
- [x] StackPath (#4652)
- [x] strongSwan (#6228)
- [x] Ted (#4653)
- [x] Trustpilot (#4481)
- [x] Uber (#4650)
- [x] Uber Eats (#4651)
- [x] Udacity (#4596)
- [x] Viber (#4597)
- [x] WP Engine (#4639)
- [x] X-Pack (#4239)
- [x] XMPP (#4483)
- [x] Zendesk (#4595)

There are still some icons listed in `.svglint-ignored.json` file that might need to be reviewed

## Icons with incorrect precision

- [x] Clubhouse (#5177)
- [x] ReactiveX (#6124)

## Icons with incorrect size

- [x] arXiv (#5884)
- [x] pre-commit (#5226)

## Icons with ineffective segments

- [x] Code Climate (#5194)
- [x] Guangzhou Metro (#6218)
- [x] Renren (#6217)
- [x] Ruby on Rails (#5167)
- [x] Sat.1 (#6219)
- [x] SparkFun (#5196)
- [x] TuneIn (#6220)

### Notes
- Rocket.Chat does not need adapting, and should be kept in the linter ignore file. Their terms specify a specific part of the icon should be in the center of the canvas.

**Comment by adamrusted** [comment]
@mondeja - in the example of Amazon Lumberyard, I'm getting the linter error of `x collinear-segments Collinear segment "l-0.01 -0.04" in path (should be removed)` - I can't find that segment in the SVG - so what's my best method of identifying where exactly this is?

**Comment by mondeja** [comment]
Keep in mind that could be part of a chained command. In this case is `l-.014-.076-.01-.04-.012-.048`. The path parser does not differentiate between a chained relative command and a direct one and because of that I'm not able to show a more accurate error message.

**Comment by adamrusted** [comment]
@mondeja I've just rebuilt Aseprite from scratch using the coordinates of the icon and writing the path out myself to avoid collinear segments, but it's still giving the error. Any chance you could take a look?

```svg
<svg role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><title>Aseprite icon</title><path d="M3.602 0H19.59v3.2h4.006v17.6h-1.598v1.6H20.4V24H3.603v-1.6h-1.6v-1.6H.404V3.2h3.197V0zm-1.6 1.6H21.19v16h-1.6v1.6H3.6v-1.6H2v-16zm6.397 4.8h-1.6v6.4h1.6V6.4zm6.395 0h1.598v6.4h-1.599V6.4z"/></svg>
```

**Comment by mondeja** [comment]
> @mondeja I've just rebuilt Aseprite from scratch using the coordinates of the icon and writing the path out myself to avoid collinear segments, but it's still giving the error. Any chance you could take a look?

You are right, I've fixed the error and will upload a pull soon.

**Comment by adamrusted** [comment]
Thanks all, with #6996 reviewed, and merging once it's finished linting properly - that's us done with the 2021 icon review! Now onto the next one!
