### ISSUE TITLE
Full Source Review

### ISSUE THREAD

**Issue by adamrusted** [simple-icons/simple-icons#5251]
I've started going through our collection a letter at a time using [_data/simple-icons.json](https://raw.githubusercontent.com/simple-icons/simple-icons/develop/_data/simple-icons.json) file to check our sources still match up. I'd appreciate any help in going through the list, to try and get through as many as possible ready for v5.0.0!

- [x] 0-9 (7 icons) @adamrusted
- [x] A (177 icons) @adamrusted
- [x] B (78 icons) @adamrusted 
- [x] C (130 icons) @adamrusted
- [x] D (77 icons) @adamrusted 
- [x] E (56 icons) @adamrusted 
- [x] F (73 icons) @adamrusted 
- [x] G (102 icons) @service-paradis 
- [x] H (65 icons) @service-paradis 
- [x] I (48 icons) @service-paradis 
- [x] J (38 icons) @service-paradis 
- [x] K (41 icons) @service-paradis 
- [x] L (59 icons) @service-paradis 
- [x] M (111 icons) @service-paradis 
- [x] N (57 icons) @service-paradis
- [x] O (50 icons) @service-paradis 
- [x] P (125 icons) @service-paradis 
- [x] Q (24 icons) @service-paradis 
- [x] R (72 icons) @service-paradis 
- [x] S (190 icons) @service-paradis
- [x] T (99 icons) @jorgeamadosoria 
- [x] U (27 icons) @adamrusted 
- [x] V (45 icons) @adamrusted
- [x] W (60 icons) @adamrusted
- [x] X (17 icons) @adamrusted
- [x] Y (16 icons) @adamrusted
- [x] Z (22 icons) @adamrusted

**Comment by jorgeamadosoria** [comment]
Finished Letter T review. 19 icons are outdated in several ways:

https://github.com/simple-icons/simple-icons/issues/6523
https://github.com/simple-icons/simple-icons/issues/6524
https://github.com/simple-icons/simple-icons/issues/6525
https://github.com/simple-icons/simple-icons/issues/6526
https://github.com/simple-icons/simple-icons/issues/6527
https://github.com/simple-icons/simple-icons/issues/6528
https://github.com/simple-icons/simple-icons/issues/6529
https://github.com/simple-icons/simple-icons/issues/6530
https://github.com/simple-icons/simple-icons/issues/6531
https://github.com/simple-icons/simple-icons/issues/6532
https://github.com/simple-icons/simple-icons/issues/6533
https://github.com/simple-icons/simple-icons/issues/6534
https://github.com/simple-icons/simple-icons/issues/6535
https://github.com/simple-icons/simple-icons/issues/6536
https://github.com/simple-icons/simple-icons/issues/6538
https://github.com/simple-icons/simple-icons/issues/6541
https://github.com/simple-icons/simple-icons/issues/6542
https://github.com/simple-icons/simple-icons/issues/6544

I will follow up 18 of these. Two of these are breaking changes, in which cases I would appreciate input on what to do.

**Comment by dirien** [comment]
If you folks need a helping hand, let me know!

**Comment by jorgeamadosoria** [comment]
> If you folks need a helping hand, let me know!

many of these are just source updates. Feel free to take any of these if you want.

**Comment by service-paradis** [comment]
I think we can close this one now! Thank you everyone involved, this was a huge tasks! 💯
