### ISSUE TITLE
A list of all popular technologies/brands/companies that are missing from SimpleIcons

### ISSUE THREAD

**Issue by DoronBrayer** [simple-icons/simple-icons#625]
It's going to be overwhelming, it's a lot...
Here is a list of all popular technologies/brands/companies that are missing from SimpleIcons:

- [ ] .NET
- [ ] Adobe PhoneGap
- [ ] Adobe XD (Experience Design)
- [ ] AFNetworking
- [ ] Akismet
- [ ] Alamofire
- [ ] Alibaba Dubbo
- [ ] Alibaba Weex
- [ ] Amazon Aurora
- [ ] Amazon EC2
- [ ] Amazon S3
- [ ] Amazon SES
- [x] AMD
- [ ] Animate.css
- [ ] Ansible
- [ ] Apache
- [ ] Apache Cassandra
- [ ] Apache Cordova [formerly PhoneGap]
- [ ] Apache CouchDB
- [ ] Apache Hive
- [ ] Apache Solr
- [ ] Apache Sprak
- [ ] Apple iCloud
- [ ] ASP.NET
- [ ] Aurelia
- [ ] Autodesk
- [ ] AWS (Amazon Web Services)
- [ ] Babel
- [ ] Backbone.js
- [ ] Beego
- [x] Bower
- [ ] Brackets
- [ ] Bulma
- [ ] ~C~ (duplicate of #469)
- [ ] C# (C Sharp)
- [ ] ~C++~ (duplicate of #469)
- [ ] Caddy
- [ ] certbot
- [ ] Ceylon
- [ ] Chart.js
- [x] Chrome (#695)
- [ ] Cloud Foundry
- [ ] CockroachDB
- [ ] ~CoffeeScript~ (duplicate of #469)
- [ ] CryEngine
- [ ] D3.js
- [ ] Debian
- [x] ElasticSearch
- [ ] Electron
- [ ] Element toolkit
- [ ] Elixir
- [ ] Elm
- [ ] Ember
- [ ] Erlang
- [ ] Express
- [ ] Fastlane
- [ ] Firebase
- [x] Firefox
- [ ] Flask
- [ ] Flux
- [ ] GIMP
- [ ] Gin-Gonic
- [x] ~GitLab~ (already exists)
- [ ] Go (Golang)
- [ ] GoDaddy
- [ ] Gogs
- [ ] Google Cloud Platform
- [ ] Grafana
- [ ] Grunt
- [ ] Handlebars
- [ ] Hugo
- [ ] Impress.js
- [ ] IntelliJ
- [ ] IntelliJ IDEA
- [x] Internet Explorer 10 / Internet Explorer 11 (#696)
- [ ] Ionic
- [ ] iOS
- [ ] Jasmine
- [ ] ~Java~ (duplicate of #469)
- [ ] Jest
- [ ] JetBrains
- [ ] KeyCDN
- [ ] KeystoneJS
- [ ] Knockout
- [ ] Koa
- [ ] Kubernetes
- [ ] LESS
- [ ] libGDX
- [ ] LibreOffice
- [ ] macOS
- [ ] MariaDB
- [ ] Material UI
- [ ] Materialize
- [ ] MaxCDN
- [ ] Maxthon
- [ ] MDL (Material Design Lite)
- [x] ~Microsoft Access~ (already exists)
- [ ] Microsoft Azure
- [x] Microsoft Edge
- [ ] ~Microsoft OneDrive~ (already exists, but perhaps the Microsoft prefix should be added)
- [ ] Microsoft SQL Server
- [ ] Moby
- [ ] Mocha
- [ ] ~MongoDB~ (duplicate of #487)
- [ ] NetBeans IDE
- [ ] Next.js
- [ ] Normalize.css
- [ ] NW.js [formerly Node-Webkit]
- [ ] OpenGL
- [ ] Oracle
- [ ] Oracle Database [commonly referred to as Oracle RDBMS or simply as Oracle]
- [ ] Paint.NET
- [ ] Phaser
- [x] ~Photoshop~ (already exists)
- [x] ~PHP~ (duplicate of #469)
- [ ] phpMyAdmin
- [ ] PhpStorm
- [ ] PingCap TiDB
- [ ] PixiJS
- [ ] Pixlr
- [ ] PostCSS
- [ ] PostgreSQL
- [ ] Prometheus - Monitoring system
- [ ] PyCharm
- [x] ~Python~ (duplicate of #469)
- [ ] Quill
- [ ] R (The R Project)
- [ ] Rackspace
- [ ] React Native
- [ ] Realm DB
- [ ] Red Hat
- [ ] ~Redis~ (duplicate of #487, also #613)
- [ ] RubyMine
- [x] ~Rust~ (duplicate of #469)
- [ ] Safari (#697)
- [ ] Sails
- [ ] SAP
- [ ] SAP HANA
- [ ] Scrapy
- [ ] Selenium
- [ ] Semantic UI
- [ ] Sequelize
- [ ] Serverless
- [ ] Sketch
- [ ] socket.io
- [ ] Source Engine
- [ ] Spring Framework
- [ ] SQLite
- [ ] SSH (Secure Shell)
- [ ] Stylus (#694)
- [ ] ~Swift~ (duplicate of #469)
- [ ] Syncthing
- [ ] TensorFlow
- [ ] three.js
- [ ] Tomcat
- [ ] ~Travis CI~ (already exists)
- [ ] ~Trello~ (already exists)
- [ ] TypeScript
- [ ] Unity
- [ ] Unreal Engine
- [ ] Vagrant
- [ ] Vapor
- [ ] VideoJS
- [ ] ~Vim~ (duplicate of #487, also #629)
- [ ] Visual Studio IDE
- [ ] W3C (World Wide Web Consortium)
- [ ] WebGL
- [x] Webpack
- [ ] Weebly
- [ ] WooCommerce
- [ ] WP Jetpack
- [ ] Yarn
- [ ] Yii PHP Framework
- [ ] Yoast SEO
- [ ] Zurb Foundation

175 icons in total. It's a lot, as I mentioned.
I hope you'll take at least half of the list into consideration.

Good luck :-)

Reference
https://github.com/kamranahmedse/developer-roadmap
https://github.com/topics
https://github.com/topics/framework?o=desc&s=stars
https://github.com/topics/css?o=desc&s=stars
https://github.com/topics/javascript?o=desc&s=stars
https://github.com/topics/html?o=desc&s=stars
https://github.com/topics/python?o=desc&s=stars
https://github.com/topics/php?o=desc&s=stars
https://github.com/topics/java?o=desc&s=stars
https://github.com/topics/android?o=desc&s=stars
https://github.com/topics/ios?o=desc&s=stars
https://github.com/topics/sql?o=desc&s=stars
https://github.com/topics/nodejs?o=desc&s=stars
https://github.com/topics/swift?o=desc&s=stars
https://github.com/topics/go?o=desc&s=stars
https://github.com/topics/linux?o=desc&s=stars
https://github.com/topics/devops?o=desc&s=stars
https://github.com/topics/database?o=desc&s=stars
https://stackoverflow.com/tags

**Comment by ericcornelissen** [comment]
Hey, thanks for the suggestions, it's a long list indeed 😅 I took the liberty of changing your issue a little bit, "removing" some duplicates (issue already existed) and some icons that we already have 👍

**Comment by DoronBrayer** [comment]
@ericcornelissen 
Thanks for the quick response.
I want to contribute. Please give a list of 20 icons to produce.
I'm actually new at this SVG stuff, but I'll do my best.

**Comment by davidklebanoff** [comment]
@DoronBrayer We really do need a nice how-to section on how to prepare a logo for addition to SimpleIcons as an icon for new contributors. My quick guidance is to identify SVGs (and color) on official websites and brand guidelines and to make use of online tools such as IcoMoon and SVGOMG or offline tools like Inkscape and SVGO to prepare the SVG appropriately. Follow the [contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and look at current icons as helpful examples.

**Comment by ericcornelissen** [comment]
@DoronBrayer As davidklebanoff said the easiest thing to do (especially if you're new to SVGs) is to look for official website/brand guidelines/official wikis and find the ones that just give you an `.svg` file. Then modify it according to the [contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and open a PR.

After a quick Google search I found a few:
- [PostgreSQL](https://wiki.postgresql.org/wiki/Logo) (searched for "PostgreSQL branding")
- [Webpack](https://webpack.js.org/branding/) (searched for "webpack branding")
- [Yarn](https://yarnpkg.com/en/) (in the header of the website, searched for "yarn branding')
- [Unreal Engine](https://commons.wikimedia.org/wiki/File:Unreal_Engine_Logo.svg) (searched or "Unreal Engine logo svg", but mayble look if you can find one of the official site)

I think you get the gist 😄 Go ahead and start with these and after that look for `.svg` files of other brands

If you want to get more advanced and get SVGs of brands that don't provide one out of the box, you'll have to get some software for that. If you want to try that I suggest picking a very simple logo (straight edges, no holes, etc.) and using some tool to transform the image to a vector image. Unfortunately I only have experience with Adobe Illustrator (which is not free), so I can't recommend any free tools. However if you search for "adobe illustrator alternatives" I'm sure you can find a tool that works for you 👍

**Comment by DoronBrayer** [comment]
@davidklebanoff / @ericcornelissen Got it, thanks. I'll get to work then.

Btw: I really believe in this project :smiley:

**Comment by davidklebanoff** [comment]
Thanks @DoronBrayer.

The [Contribution Guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) have just been given a big update. Hopefully you find it a little more helpful than the previous version.

**Comment by DoronBrayer** [comment]
@davidklebanoff / @ericcornelissen Question: What is the best technique/tool to merge multiple paths into a single path?

**Comment by ericcornelissen** [comment]
I'm not sure, I know it is very easy in Adobe Illustrator... But from [stackexchange](https://graphicdesign.stackexchange.com/questions/45611/how-do-i-merge-these-two-objects-in-inkscape-such-that-the-space-in-between-is-g) I found that you can do it in Inkscape as follows:

> Select all [three] objects to create a unified object <kbd>Ctrl</kbd> + <kbd>+</kbd>

**Comment by DoronBrayer** [comment]
@ericcornelissen The [CTRL]+[+] ("Union" action) is destroying some of the objects.
I'm really struggling to create a single path.

**Comment by ericcornelissen** [comment]
@DoronBrayer that's unfortunate 🤔 we should find a good solution for that or reconsider that point in the contributing guidelines /cc @davidklebanoff 

For now you can open a PR (you have my blessing 😉) just be sure to allow maintainers to edit your PR (there is a checkbox for that when you create it) and I will see if I can fix the path problem for you 👍

**Comment by davidklebanoff** [comment]
I let the SVGO optimization process merge multiple paths into a single path.

For simple changes, like removing color, scaling, centering, and deleting individual paths, I use Icomoon because it's so easy. For more complex changes, such as unions and differences, I use Inkscape.

In Inkscape, I find the tools in the `path` menu in the top menu are very useful. Union, difference, intersection, etc. I also found it's useful to do only two paths at a time. Do note, I believe the order you select the paths has an impact on the end result, at least for destructive processes like difference.

As for the contribution guidelines, I wanted to keep them tool agnostic, since everyone has a different tool they like to use. I also wanted to keep them simple so they're not too intimidating. And finally, I didn't think it was an appropriate place to have a tutorial on how to use various tools.

With that said, if you or anyone would like to improve upon them, please do!

If people would like to create guides that walk new contributors through how to use the various tools to help contribute to this project, I think a separate doc or wiki would be a good place and we could link to those from the contribution guidelines.

**Comment by davidklebanoff** [comment]
@DoronBrayer Also, it seems PR #645 may be challenging our assumption that all icons should be a single path. More investigation is needed.

**Comment by ericcornelissen** [comment]
@DoronBrayer, as of #644 you no longer have to worry about multiple `<path>`s 👍

**Comment by DoronBrayer** [comment]
@ericcornelissen / @davidklebanoff Thanks. I actually like the idea of keeping a single path in each SVG, especially when this project called '**Simple**Icons'.
I think that if it's possible to make a good icon with short/simple code, we should do it.
However, sometimes it's not possible.
With that in mind, you should encourage the contributors to try reduce the amount of paths as much as possible, because there are some very bloated SVGs out there (even in official sources).

**Comment by ericcornelissen** [comment]
@DoronBrayer, I agree but as of now we can't enforce the single `<path>` rule, since we aren't sure if that is actually the best solution. That being said, by encouraging users to use tools such as SVGO the icons of SimpleIcons should be reasonably short/simple 👍

**Comment by tomap** [comment]
Hi, not sure it's the right place, but I'd like to vote for firebase
Here are the guidelines https://firebase.google.com/brand-guidelines/

**Comment by davidklebanoff** [comment]
Closing due to lack of activity. If there is an icon on this list that anyone would like to be added 
to Simple Icons, please:

1. Check to see if it has not already been added.
1. Create a new Icon Request issue for the desired icon.

In the future, for better organization and a higher likelihood of the icons to be added, it's best to limit the size of icon requests to a smaller number of icons per issue. Requests should perhaps be limited to:
- a single brand (e.g. Google)
- a few brands that share a common theme (e.g. "Social Networks")
- a collection of closely related brands (e.g. "Adobe Photoshop", "Adobe Illustrator", etc...).

The inclusion of the 150+ technology brands in this particular issue is perhaps a bit too ambitious.
