### ISSUE TITLE
Microsoft Power Platform Icons

### ISSUE THREAD

**Issue by adamrusted** [simple-icons/simple-icons#7780]
### Brand Name

Power Platform

### Website

None

### Popularity Metric

Microsoft's citizen developer platform, made up of the below components (most of which already in the collection, but I'll check for any updates.
- [x] Dataverse (Added in #7782)
- [x] Power Apps (Already exists, updated in #7781)
- [x] Power Automate (Already exists, updated in #7785)
- [x] Power BI (Already exists, updated in #7784)
- [x] PowerFx (Added in #7788)
- [x] Power Pages (Added in #7783)
- [x] Power Platform (Added in #7779)
- [x] Power Virtual Agents (Already exists, updated in #7786)

### Official Resources for Icon and Color

https://docs.microsoft.com/en-us/power-platform/guidance/icons

### Additional Comments

Would like feedback from maintainers before I put the work in on most of these. Would you be okay to add these in without a popularity metric other than "They're a pretty big deal in the Microsoft world"?

### Contributing

Yes

**Comment by LitoMore** [comment]
LGTM

**Comment by adamrusted** [comment]
I'll put some time in this weekend getting them all put together then. Thanks @LitoMore!
