### ISSUE TITLE
Request: File Hosting Sites

### ISSUE THREAD

**Issue by Adamanthus** [simple-icons/simple-icons#805]
Would be nice if some of the more common file hosting services could be added. GOG seem to have some suitable SVG's. I think these 5 are very well known.

- [x] Mediafire (https://www.onlinewebfonts.com/icon/432848)
- [x] MEGA (https://commons.wikimedia.org/wiki/File:01_mega_logo.svg)
- [x] Uploaded (https://goggames.goodolddownloads.com/static/img/hoster_logos/uploaded.svg}
- [x] UpToBox (https://goggames.goodolddownloads.com/static/img/hoster_logos/uptobox.svg)
- [x] Zippyshare (https://goggames.goodolddownloads.com/static/img/hoster_logos/zippyshare.svg)

**Comment by birjolaxew** [comment]
Official logo sources:

- [Mediafire](https://www.mediafire.com/press/)
- [MEGA](https://mega.nz/corporate/page-2) (PNG only; use the Wikimedia link for SVG)
- Uploaded - ? Link is dead, googling gives nothing, never heard of the service.
- UpToBox - no high quality logo available. Poor PNG at [their site](http://uptobox.com/)
- ZippyShare - no high quality logo available. Poor PNG at [their site](http://www.zippyshare.com/)

ZippyShare is going to be difficult to turn monochrome, and since there isn't a high quality logo available, I'd say it isn't really worth the hassle (unless someone feels like putting in the work of course :wink:). Although UpToBox is easy to turn monochrome, the logo is so poor quality that the same goes there.

**Comment by Adamanthus** [comment]
Uploaded has been around a long time. The site is https://uploaded.net/
Zippyshare announced a new logo on their blog but it's just a png @ http://blog.zippyshare.com/z.png and they haven't applied their redesign yet so I guess it's not 'current'.

Are the GOG SVG's not suitable?

**Comment by birjolaxew** [comment]
I suppose the name just gave too many irrelevant hits (also the logo link is 404).

We prefer to use official sources for our logos, with the option of falling back onto a reputable neutral source (usually Wikimedia) if one isn't available. Third parties (e.g. GOG) aren't usually used, unless the logo is checked carefully to match official sources exactly.

**Comment by Adamanthus** [comment]
https://goggames.goodolddownloads.com/static/img/hoster_logos/uploaded.svg works for me and fair enough if these requests cannot be met :)

**Comment by Adorable-SkullMaster** [comment]
Uploaded, UpToBox and ZippyShare are extremely popular for piracy media hosting. Kinda famous for Piracy.
Also Mega is also quite popular in this area, except that Mega is a quite more professional service. More like Google Drive.

**Comment by jorgeamadosoria** [comment]
Adding uptobox: https://github.com/simple-icons/simple-icons/pull/6244
I personally don't like it, but there are no high definition logos to get anything else from.

**Comment by jorgeamadosoria** [comment]
Added a (badly drawn) zippyshare logo here: https://github.com/simple-icons/simple-icons/pull/6245

This should be enough to close this ticket.

Semi unrelatedly, I guess The Pirate Bay is out of the question, right?

**Comment by ericcornelissen** [comment]
> Semi unrelatedly, I guess The Pirate Bay is out of the question, right?

It's slightly tricky but I would say so. I couldn't find an explicit text saying this in my 10 second search, but the name is a strong suggestion that it (at least) supports an "illegal" activity, namely pirating software (and other digital products).


> This should be enough to close this ticket.

Agreed :+1:

**Comment by jorgeamadosoria** [comment]
There are Pull Requests for zippyshare and uptobox icons pending review, although given the low quality of the sources I'm not optimistic about their chances. 
We can close the ticket now and continue discussion in those PRs.
